/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c653c1b574a02ff90477944ad5e6c316)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
